# Generated by Django 4.2.5 on 2023-09-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dine_in',
            field=models.BooleanField(null=True),
        ),
    ]
