# Generated by Django 4.2.5 on 2023-09-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='days',
            new_name='daze',
        ),
    ]
