# Generated by Django 4.2.5 on 2023-09-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_days_day_daze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='daze',
            new_name='days',
        ),
    ]
