# Generated by Django 3.2.12 on 2023-09-17 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurant_closing_time_restaurant_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday')], default='SU', max_length=2)),
                ('opening_time', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('closing_time', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='days',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='days',
            field=models.ManyToManyField(to='main_app.Days'),
        ),
    ]
