# Generated by Django 4.2.5 on 2023-09-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_days_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
            preserve_default=False,
        ),
    ]
